server:
  port: 8080

spring:
  datasource:
    name: test
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/kindergarten?serverTimezone=UTC&useUnicode=true&characterEncoding=UTF-8
    username: root
    password: 123456

  mvc:
    view:
      prefix : /WEB-INF/jsp/
      suffix : .jsp


